services:
  postgres:
    container_name: db_book_server
    image: postgres:latest
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5433:5432'

  adminer:
    container_name: adminer_server
    image: adminer
    ports:
      - '9000:8080'